import jsPDF from 'jspdf';

interface AnalysisData {
  label: string;
  type: string;
  category: string;
  degradability: string;
  imageUrl: string;
  environmentalImpact: string[];
  harms: string[];
  disposal: string[];
  alternatives: string[];
  recommendations: any;
  potentialForReuse: string;
  createdAt: string;
  user?: {
    name?: string;
    email?: string;
  };
}

export async function generateAnalysisPDF(data: AnalysisData): Promise<void> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPos = margin;

  // Helper function to add a new page if needed
  const checkPageBreak = (requiredHeight: number) => {
    if (yPos + requiredHeight > pageHeight - margin) {
      doc.addPage();
      yPos = margin;
    }
  };

  // Title
  doc.setFontSize(24);
  doc.setTextColor(0, 0, 0);
  doc.text('Environmental Analysis Report', margin, yPos);
  yPos += 10;

  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by Ecoverse - ${new Date().toLocaleDateString()}`, margin, yPos);
  yPos += 15;

  // Image (if available)
  if (data.imageUrl) {
    try {
      checkPageBreak(60); // Reserve space for image
      
      let imageDataUrl = data.imageUrl;
      
      // If URL is not a data URL, fetch and convert it
      if (!imageDataUrl.startsWith('data:')) {
        try {
          const imgResponse = await fetch(imageDataUrl);
          if (imgResponse.ok) {
            const blob = await imgResponse.blob();
            const reader = new FileReader();
            imageDataUrl = await new Promise<string>((resolve, reject) => {
              reader.onloadend = () => resolve(reader.result as string);
              reader.onerror = reject;
              reader.readAsDataURL(blob);
            });
          }
        } catch (fetchError) {
          console.warn('Could not fetch image, skipping:', fetchError);
          // Continue without image
        }
      }
      
      // Calculate image dimensions to fit within content width
      const maxImageWidth = contentWidth;
      const maxImageHeight = 50; // Max height in mm
      
      // Get image dimensions using browser Image API (if available)
      let imgWidth = maxImageWidth;
      let imgHeight = maxImageHeight;
      
      if (typeof window !== 'undefined' && typeof Image !== 'undefined') {
        try {
          const img = new Image();
          await new Promise<void>((resolve, reject) => {
            img.onload = () => resolve();
            img.onerror = reject;
            img.src = imageDataUrl;
          });
          
          // Calculate aspect ratio and scale
          const aspectRatio = img.width / img.height;
          imgWidth = maxImageWidth;
          imgHeight = imgWidth / aspectRatio;
          
          if (imgHeight > maxImageHeight) {
            imgHeight = maxImageHeight;
            imgWidth = imgHeight * aspectRatio;
          }
        } catch (imgError) {
          console.warn('Could not get image dimensions, using defaults:', imgError);
        }
      }
      
      // Center the image
      const imgX = margin + (contentWidth - imgWidth) / 2;
      
      // Add image to PDF
      // Determine image format from data URL or default to JPEG
      const imageFormat = imageDataUrl.includes('data:image/png') ? 'PNG' : 'JPEG';
      doc.addImage(imageDataUrl, imageFormat, imgX, yPos, imgWidth, imgHeight);
      yPos += imgHeight + 10;
    } catch (error) {
      console.error('Error adding image to PDF:', error);
      // Continue without image if there's an error
    }
  }

  // Item Information
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.setFont(undefined, 'bold');
  doc.text('Item Information', margin, yPos);
  yPos += 8;

  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(60, 60, 60);
  
  const itemInfo = [
    ['Item:', data.label || 'Unknown'],
    ['Material Type:', data.type || 'Unknown'],
    ['Category:', data.category || 'Uncategorized'],
    ['Degradability:', data.degradability || 'Not specified'],
  ];

  itemInfo.forEach(([label, value]) => {
    checkPageBreak(8);
    doc.setFont(undefined, 'bold');
    doc.text(label, margin, yPos);
    doc.setFont(undefined, 'normal');
    // Wrap long values to prevent overflow
    const valueLines = doc.splitTextToSize(value, contentWidth - 40);
    valueLines.forEach((line: string, index: number) => {
      if (index > 0) {
        checkPageBreak(6);
        yPos += 6;
      }
      doc.text(line, margin + 40, yPos);
    });
    yPos += 7;
  });

  yPos += 5;

  // Environmental Impact
  if (data.environmentalImpact && data.environmentalImpact.length > 0) {
    checkPageBreak(15);
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Environmental Impact', margin, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(60, 60, 60);
    
    data.environmentalImpact.forEach((impact: string) => {
      checkPageBreak(8);
      // Wrap long text to prevent overflow
      const impactLines = doc.splitTextToSize(`• ${impact}`, contentWidth - 10);
      impactLines.forEach((line: string, index: number) => {
        if (index > 0) {
          checkPageBreak(6);
        }
        doc.text(line, margin + 5, yPos);
        yPos += 6;
      });
    });
    yPos += 5;
  }

  // Health Risks
  if (data.harms && data.harms.length > 0) {
    checkPageBreak(15);
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Health Risks', margin, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(60, 60, 60);
    
    data.harms.forEach((harm: string) => {
      checkPageBreak(8);
      // Wrap long text to prevent overflow
      const harmLines = doc.splitTextToSize(`• ${harm}`, contentWidth - 10);
      harmLines.forEach((line: string, index: number) => {
        if (index > 0) {
          checkPageBreak(6);
        }
        doc.text(line, margin + 5, yPos);
        yPos += 6;
      });
    });
    yPos += 5;
  }

  // Disposal Instructions
  if (data.disposal && data.disposal.length > 0) {
    checkPageBreak(15);
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Disposal Instructions', margin, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(60, 60, 60);
    
    data.disposal.forEach((instruction: string) => {
      checkPageBreak(8);
      // Wrap long text to prevent overflow
      const instructionLines = doc.splitTextToSize(`• ${instruction}`, contentWidth - 10);
      instructionLines.forEach((line: string, index: number) => {
        if (index > 0) {
          checkPageBreak(6);
        }
        doc.text(line, margin + 5, yPos);
        yPos += 6;
      });
    });
    yPos += 5;
  }

  // Alternatives
  if (data.alternatives && data.alternatives.length > 0) {
    checkPageBreak(15);
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Eco-Friendly Alternatives', margin, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(60, 60, 60);
    
    data.alternatives.forEach((alternative: string) => {
      checkPageBreak(8);
      // Wrap long text to prevent overflow
      const alternativeLines = doc.splitTextToSize(`• ${alternative}`, contentWidth - 10);
      alternativeLines.forEach((line: string, index: number) => {
        if (index > 0) {
          checkPageBreak(6);
        }
        doc.text(line, margin + 5, yPos);
        yPos += 6;
      });
    });
    yPos += 5;
  }

  // Recommendations
  if (data.recommendations && typeof data.recommendations === 'object') {
    checkPageBreak(15);
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Recommendations', margin, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(60, 60, 60);
    
    if (data.recommendations.reduce) {
      checkPageBreak(10);
      doc.setFont(undefined, 'bold');
      doc.text('Reduce:', margin + 5, yPos);
      yPos += 6;
      doc.setFont(undefined, 'normal');
      const reduceLines = doc.splitTextToSize(data.recommendations.reduce, contentWidth - 10);
      reduceLines.forEach((line: string) => {
        checkPageBreak(6);
        doc.text(line, margin + 10, yPos);
        yPos += 6;
      });
      yPos += 3;
    }
    
    if (data.recommendations.reuse) {
      checkPageBreak(10);
      doc.setFont(undefined, 'bold');
      doc.text('Reuse:', margin + 5, yPos);
      yPos += 6;
      doc.setFont(undefined, 'normal');
      const reuseLines = doc.splitTextToSize(data.recommendations.reuse, contentWidth - 10);
      reuseLines.forEach((line: string) => {
        checkPageBreak(6);
        doc.text(line, margin + 10, yPos);
        yPos += 6;
      });
      yPos += 3;
    }
    
    if (data.recommendations.recycle) {
      checkPageBreak(10);
      doc.setFont(undefined, 'bold');
      doc.text('Recycle:', margin + 5, yPos);
      yPos += 6;
      doc.setFont(undefined, 'normal');
      const recycleLines = doc.splitTextToSize(data.recommendations.recycle, contentWidth - 10);
      recycleLines.forEach((line: string) => {
        checkPageBreak(6);
        doc.text(line, margin + 10, yPos);
        yPos += 6;
      });
    }
    yPos += 5;
  }

  // Reuse Potential
  if (data.potentialForReuse) {
    checkPageBreak(15);
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Reuse Potential', margin, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(60, 60, 60);
    const reuseLines = doc.splitTextToSize(data.potentialForReuse, contentWidth);
    reuseLines.forEach((line: string) => {
      checkPageBreak(6);
      doc.text(line, margin, yPos);
      yPos += 6;
    });
    yPos += 5;
  }

  // Footer
  // getNumberOfPages is available at runtime but not always in the TypeScript typings
  const totalPages = (doc as any).getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${totalPages} - Generated by ${data.user?.name || data.user?.email || 'Anonymous'} on ${new Date(data.createdAt).toLocaleDateString()}`,
      margin,
      pageHeight - 10
    );
    doc.text(
      'Powered by Ecoverse - Environmental Analysis Platform',
      pageWidth - margin - 60,
      pageHeight - 10
    );
  }

  // Save the PDF
  doc.save(`ecoverse-analysis-${data.label.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${Date.now()}.pdf`);
}

